name: Main Merge Automation

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - 'main'

jobs:
  check_title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        run: |
          pr_title=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
          title_pattern="^DEPLOY : (BE|FE|AI) - .*"
          if [[ ! $pr_title =~ $title_pattern ]]; then
            echo "error :: The PR title does not match the expected format."
            echo "error :: Please follow this format: '파트명-기능명/기능타입'"
            echo "error :: Example: 'be-api/test'"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
